### ISSUE TITLE
HashMap load factor visual bug

### ISSUE THREAD

**Issue by skapoor68** [RodrigoDLPontes/visualization-tool#251]
The load factor input for hashmaps is formatted weirdly. This might stem from changes made in #249.

<img width="266" alt="Screenshot 2023-05-26 at 1 17 22 AM" src="https://github.com/RodrigoDLPontes/visualization-tool/assets/96704494/b94a72df-5ae6-4471-a69f-91b343ed8394">

**Comment by luciankt** [comment]
I made this change intentionally since I think it's more intuitive than the previous input label, which just said `LF/100`. It's supposed to look like you're typing in the decimal for the load factor. But on second thought, it might be better to instead have the input field and a % sign, like `[  ]%`. That would also allow for values greater than 100%, which is not currently supported, but could be for External Chaining. What do you think?

**Comment by skapoor68** [comment]
Using the percent sign followed by the input field seems best. I plan to make a PR later this week with some other changes and I'll try to incorporate this change as well!

**Comment by luciankt** [comment]
Sounds good!
